spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_database
    password: root
    username: postgres


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 50
          fetch_size: 50



logging:
  level:
    root: INFO
    org.hibernate.sql: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"


info:
  app:
    name: Simple spring boot project
    version: v.1.1
    description: simple banking application.
